# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0075_course_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='lock_down_sessions',
        ),
    ]
