# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0077_various_model_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='editor_mode',
            field=models.CharField(choices=[(b'default', 'Default'), (b'sublime', b'Sublime text'), (b'emacs', b'Emacs'), (b'vim', b'Vim')], default=b'default', help_text="Which key bindings you prefer when editing larger amounts of text or code. (If you do not understand what this means, leave it as 'Default'.)", max_length=20, verbose_name='Editor mode'),
        ),
    ]
