# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0078_help_tweak'),
    ]

    operations = [
        migrations.AddField(
            model_name='participationtag',
            name='shown_to_participant',
            field=models.BooleanField(default=False, verbose_name='Shown to pariticpant'),
        ),
    ]
