# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 05:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0079_participationtag_shown_to_participant'),
        ('accounts', '0007_migrate_user_status_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstatus',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserStatus',
        ),
    ]
