# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0083_participation_user_relatedname'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowsession',
            name='page_data_at_course_revision',
            field=models.CharField(blank=True, help_text='Page set-up data is up-to date for this revision of the course material', max_length=200, null=True, verbose_name='Page data at course revision'),
        ),
    ]
