# Generated by Django 1.9.1 on 2016-02-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0086_flowpagedata_bookmarked'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingopportunity',
            name='page_scores_in_participant_gradebook',
            field=models.BooleanField(default=False, verbose_name="Scores for individual pages are shown in the participants' grade book"),
        ),
    ]
