# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-14 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0087_gradingopportunity_page_scores_in_participant_gradebook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradingopportunity',
            old_name='shown_in_student_grade_book',
            new_name='shown_in_participant_grade_book',
        ),
    ]
