# Generated by Django 1.9.2 on 2016-03-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0088_rename_shown_in_participant_grade_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingopportunity',
            name='hide_superseded_grade_history_before',
            field=models.DateTimeField(blank=True, help_text='Grade changes dated before this date that are superseded by later grade changes will not be shown to participants. This can help avoid discussions about pre-release grading adjustments.May be blank. In that case, the entire grade history is shown.', null=True, verbose_name='Hide superseded grade history before'),
        ),
    ]
