# Generated by Django 1.10 on 2016-09-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0095_minor_model_tweaks'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
    ]
