# Generated by Django 1.10 on 2016-09-12 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0096_participation_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participationrolepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='course.ParticipationRole', verbose_name='Role'),
        ),
    ]
