# Generated by Django 1.10.2 on 2016-10-28 08:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0097_add_permissions_related_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowaccessexceptionentry',
            name='permission',
            field=models.CharField(
                choices=[('view', 'View the flow'), ('submit_answer', 'Submit answers'), ('end_session', 'End session'),
                         ('change_answer', 'Change already-graded answer'),
                         ('see_correctness', 'See whether an answer is correct'),
                         ('see_answer_before_submission', 'See the correct answer before answering'),
                         ('see_answer_after_submission', 'See the correct answer after answering'),
                         ('cannot_see_flow_result', 'Cannot see flow result'),
                         ('set_roll_over_expiration_mode', "Set the session to 'roll over' expiration mode"),
                         ('see_session_time', 'See session time'),
                         ('lock_down_as_exam_session', 'Lock down as exam session'),
                         ('send_email_about_flow_page', 'Send emails about the flow page to course staff')],
                max_length=50,
                verbose_name='Permission'),
        ),
    ]
