# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 02:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0098_alter_flowaccessexceptionentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradingopportunity',
            name='identifier',
            field=models.CharField(help_text='A symbolic name for this grade. lower_case_with_underscores, no spaces.', max_length=200, validators=[django.core.validators.RegexValidator('^(?P<grading_opp_id>[-_a-zA-Z0-9]+)$', message="Identifier may only contain letters, numbers, and hypens ('-').")], verbose_name='Grading opportunity ID'),
        ),
    ]
