# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-19 02:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0106_add_auth_tokens_permission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flowpagedata',
            old_name='ordinal',
            new_name='page_ordinal',
        ),
    ]
