# Generated by Django 1.10.7 on 2017-12-19 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0107_rename_flowpagedata_ordinal_to_page_ordinal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowpagedata',
            name='page_ordinal',
            field=models.IntegerField(blank=True, null=True, verbose_name='Page ordinal'),
        ),
    ]
