# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-29 03:26
from __future__ import unicode_literals

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0109_add_manage_authentication_tokens_permssion'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='force_lang',
            field=models.CharField(blank=True, default='', help_text='Which language is forced to be used for this course.', max_length=200, null=True, validators=[course.models.validate_course_specific_language], verbose_name='Course language forcibly used'),
        ),
    ]
