# Generated by Django 1.11.8 on 2018-01-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0110_add_force_lang_field_to_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='git_source',
            field=models.CharField(help_text="A Git URL from which to pull course updates. If you're just starting out, enter <tt>git://github.com/inducer/relate-sample</tt> to get some sample content.", max_length=200, verbose_name='git source'),
        ),
    ]
