# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-24 09:04
from __future__ import unicode_literals

from django.db import migrations, models


def set_default_previous_completion_time(apps, schema_editor):
    FlowSession = apps.get_model("course", "FlowSession")  # noqa
    target_flow_sessions = FlowSession.objects.filter(
        in_progress=False
    )
    for fs in target_flow_sessions:
        fs.previous_completion_time = fs.previous_completion_time
        fs.save()


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0111_alter_git_source_in_course_to_a_required_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowsession',
            name='previous_completion_time',
            field=models.DateTimeField(blank=True,
                                       help_text='The last completion time for an in-progress flow session, which had been submitted and then reopened.',
                                       null=True,
                                       verbose_name='Previous completion time'),
        ),
        migrations.RunPython(set_default_previous_completion_time)
    ]
