# Generated by Django 2.2.4 on 2019-09-19 17:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0111_alter_git_source_in_course_to_a_required_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participationtag',
            name='name',
            field=models.CharField(help_text='Format is lower-case-with-hyphens. Do not use spaces.', max_length=100, verbose_name='Name of participation tag'),
        ),
    ]
