# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-20 03:00
from __future__ import unicode_literals

from django.db import migrations, models

def set_grade_change_effective_time(apps, schema_editor):
    GradeChange = apps.get_model("course", "GradeChange")  # noqa
    target_grade_changes = GradeChange.objects.filter(
        flow_session__isnull=False,
    ).select_related("flow_session")
    for gc in target_grade_changes:
        if not gc.flow_session.in_progress:
            gc.effective_time = gc.flow_session.completion_time
            gc.save()


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0111_alter_git_source_in_course_to_a_required_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradechange',
            name='effective_time',
            field=models.DateTimeField(
                blank=True, default=None,
                help_text=('The time matching the completion time of the '
                           'related event. For example, the completion time '
                           'the of the related flow session'),
                null=True, verbose_name='Effective time'),
        ),
        migrations.RunPython(set_grade_change_effective_time),
    ]
