# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-25 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0112_add_previous_completion_time_to_flow_session'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authenticationtoken',
            options={'ordering': ('participation', 'creation_time'), 'verbose_name': 'Authentication token', 'verbose_name_plural': 'Authentication tokens'},
        ),
        migrations.AlterField(
            model_name='gradechange',
            name='state',
            field=models.CharField(choices=[('grading_started', 'Grading started'), ('graded', 'Graded'), ('retrieved', 'Retrieved'), ('unavailable', 'Unavailable'), ('extension', 'Extension'), ('report_sent', 'Report sent'), ('do_over', 'Do-over'), ('exempt', 'Exempt'), ('session_reopened', 'Session reopened')], max_length=50, verbose_name='State'),
        ),
    ]
