# Generated by Django 2.2.4 on 2019-09-19 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0112_drop_name_uniqueness_on_participationtag'),
        ('course', '0112_add_direct_git_endpoint_permission'),
    ]

    operations = [
    ]
