# Generated by Django 3.0.8 on 2020-10-28 07:23

import course.models
import django.core.validators
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0113_merge_20190919_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='participationpreapproval',
            name='tags',
            field=models.ManyToManyField(blank=True, to='course.ParticipationTag', verbose_name='Participation tags'),
        ),
    ]
