# Generated by Django 3.0.8 on 2020-10-25 03:44

import django.core.validators
import jsonfield.fields
from django.db import migrations, models

import course.models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0113_merge_20190919_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participationrole',
            name='identifier',
            field=models.CharField(help_text="A symbolic name for this role, used in course code. Should be a valid identifier. The name 'unenrolled' is special and refers to anyone not enrolled in the course.", max_length=100, verbose_name='Role identifier'),
        ),
        migrations.AlterField(
            model_name='participationtag',
            name='name',
            field=models.CharField(help_text='Should be a valid identifier.', max_length=100, verbose_name='Name of participation tag'),
        ),
        migrations.AlterField(
            model_name='participationtag',
            name='shown_to_participant',
            field=models.BooleanField(default=False, verbose_name='Shown to participant'),
        ),
    ]
