# Generated by Django 3.0.14 on 2021-04-16 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0115_catch_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='trusted_for_markup',
            field=models.BooleanField(default=False, verbose_name='May present arbitrary HTML to course participants'),
        ),
    ]
