# Generated by Django 4.2.4 on 2023-08-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0118_git_to_http_in_git_src_descr'),
    ]

    operations = [
        migrations.AddField(
            model_name='examticket',
            name='require_login',
            field=models.BooleanField(default=False, help_text='If set, the exam ticket can only be used once logged in'),
        ),
    ]
