# Generated by Django 4.2.4 on 2023-09-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0119_examticket_require_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examticket',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
