from django.db import migrations, models

import course.constants


def add_batch_ai_grade_flow_page_permission(apps, schema_editor):
    from course.constants import ParticipationPermission as pperm

    ParticipationRolePermission = apps.get_model(
        "course", "ParticipationRolePermission")

    roles_pks = (
        ParticipationRolePermission.objects.filter(
            permission=pperm.assign_grade)
        .values_list("role", flat=True)
    )

    if roles_pks.count():
        for pk in roles_pks:
            ParticipationRolePermission.objects.get_or_create(
                role_id=pk,
                permission=pperm.batch_ai_grade_flow_page
            )


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0123_delete_flowaccessexception"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="ai_grading_api_base_url",
            field=models.CharField(
                blank=True, null=True, max_length=200,
                help_text=(
                    "(Required only if AI-assisted grading is used.) "
                    "The base URL of an OpenAI-API-compatible endpoint to "
                    "use for drafting grades."),
                verbose_name="AI grading API base URL"),
        ),
        migrations.AddField(
            model_name="course",
            name="ai_grading_api_key",
            field=models.CharField(
                blank=True, null=True, max_length=200,
                help_text=(
                    "(Required only if AI-assisted grading is used.) "
                    "The API key to use for the AI grading endpoint above."),
                verbose_name="AI grading API key"),
        ),
        migrations.AddField(
            model_name="course",
            name="ai_grading_model",
            field=models.CharField(
                blank=True, null=True, max_length=200,
                help_text=(
                    "(Required only if AI-assisted grading is used.) "
                    "The name of the model to request from the AI grading "
                    "endpoint above."),
                verbose_name="AI grading model"),
        ),
        migrations.AddField(
            model_name="flowpagevisitgrade",
            name="ai_generated_by",
            field=models.CharField(
                blank=True, null=True, max_length=200,
                help_text=(
                    "The name of the AI model that drafted this grade "
                    "(and which has not yet been reviewed by a human), or "
                    "NULL if this grade was not AI-generated."),
                verbose_name="AI-generated by"),
        ),
        migrations.AlterField(
            model_name="participationpermission",
            name="permission",
            field=models.CharField(choices=[(course.constants.ParticipationPermission["edit_course"], "Edit course"), (course.constants.ParticipationPermission["use_admin_interface"], "Use admin interface"), (course.constants.ParticipationPermission["manage_authentication_tokens"], "Manage authentication tokens"), (course.constants.ParticipationPermission["impersonate_role"], "Impersonate role"), (course.constants.ParticipationPermission["set_fake_time"], "Set fake time"), (course.constants.ParticipationPermission["set_pretend_facility"], "Pretend to be in facility"), (course.constants.ParticipationPermission["edit_course_permissions"], "Edit course permissions"), (course.constants.ParticipationPermission["view_hidden_course_page"], "View hidden course page"), (course.constants.ParticipationPermission["view_calendar"], "View calendar"), (course.constants.ParticipationPermission["send_instant_message"], "Send instant message"), (course.constants.ParticipationPermission["access_files_for"], "Access files for"), (course.constants.ParticipationPermission["included_in_grade_statistics"], "Included in grade statistics"), (course.constants.ParticipationPermission["skip_during_manual_grading"], "Skip during manual grading"), (course.constants.ParticipationPermission["edit_exam"], "Edit exam"), (course.constants.ParticipationPermission["issue_exam_ticket"], "Issue exam ticket"), (course.constants.ParticipationPermission["batch_issue_exam_ticket"], "Batch issue exam ticket"), (course.constants.ParticipationPermission["view_participant_masked_profile"], "View participants' masked profile only"), (course.constants.ParticipationPermission["view_flow_sessions_from_role"], "View flow sessions from role"), (course.constants.ParticipationPermission["view_gradebook"], "View gradebook"), (course.constants.ParticipationPermission["edit_grading_opportunity"], "Edit grading opportunity"), (course.constants.ParticipationPermission["assign_grade"], "Assign grade"), (course.constants.ParticipationPermission["view_grader_stats"], "View grader stats"), (course.constants.ParticipationPermission["batch_import_grade"], "Batch-import grades"), (course.constants.ParticipationPermission["batch_export_grade"], "Batch-export grades"), (course.constants.ParticipationPermission["batch_download_submission"], "Batch-download submissions"), (course.constants.ParticipationPermission["impose_flow_session_deadline"], "Impose flow session deadline"), (course.constants.ParticipationPermission["batch_impose_flow_session_deadline"], "Batch-impose flow session deadline"), (course.constants.ParticipationPermission["end_flow_session"], "End flow session"), (course.constants.ParticipationPermission["batch_end_flow_session"], "Batch-end flow sessions"), (course.constants.ParticipationPermission["regrade_flow_session"], "Regrade flow session"), (course.constants.ParticipationPermission["batch_regrade_flow_session"], "Batch-regrade flow sessions"), (course.constants.ParticipationPermission["recalculate_flow_session_grade"], "Recalculate flow session grade"), (course.constants.ParticipationPermission["batch_recalculate_flow_session_grade"], "Batch-recalculate flow session grades"), (course.constants.ParticipationPermission["batch_ai_grade_flow_page"], "Batch AI-draft grades for a flow page"), (course.constants.ParticipationPermission["reopen_flow_session"], "Reopen flow session"), (course.constants.ParticipationPermission["grant_exception"], "Grant exception"), (course.constants.ParticipationPermission["view_analytics"], "View analytics"), (course.constants.ParticipationPermission["preview_content"], "Preview content"), (course.constants.ParticipationPermission["update_content"], "Update content"), (course.constants.ParticipationPermission["use_git_endpoint"], "Use direct git endpoint"), (course.constants.ParticipationPermission["use_markup_sandbox"], "Use markup sandbox"), (course.constants.ParticipationPermission["use_page_sandbox"], "Use page sandbox"), (course.constants.ParticipationPermission["test_flow"], "Test flow"), (course.constants.ParticipationPermission["edit_events"], "Edit events"), (course.constants.ParticipationPermission["query_participation"], "Query participation"), (course.constants.ParticipationPermission["edit_participation"], "Edit participation"), (course.constants.ParticipationPermission["preapprove_participation"], "Preapprove participation"), (course.constants.ParticipationPermission["manage_instant_flow_requests"], "Manage instant flow requests")], db_index=True, max_length=200, verbose_name="Permission"),
        ),
        migrations.AlterField(
            model_name="participationrolepermission",
            name="permission",
            field=models.CharField(choices=[(course.constants.ParticipationPermission["edit_course"], "Edit course"), (course.constants.ParticipationPermission["use_admin_interface"], "Use admin interface"), (course.constants.ParticipationPermission["manage_authentication_tokens"], "Manage authentication tokens"), (course.constants.ParticipationPermission["impersonate_role"], "Impersonate role"), (course.constants.ParticipationPermission["set_fake_time"], "Set fake time"), (course.constants.ParticipationPermission["set_pretend_facility"], "Pretend to be in facility"), (course.constants.ParticipationPermission["edit_course_permissions"], "Edit course permissions"), (course.constants.ParticipationPermission["view_hidden_course_page"], "View hidden course page"), (course.constants.ParticipationPermission["view_calendar"], "View calendar"), (course.constants.ParticipationPermission["send_instant_message"], "Send instant message"), (course.constants.ParticipationPermission["access_files_for"], "Access files for"), (course.constants.ParticipationPermission["included_in_grade_statistics"], "Included in grade statistics"), (course.constants.ParticipationPermission["skip_during_manual_grading"], "Skip during manual grading"), (course.constants.ParticipationPermission["edit_exam"], "Edit exam"), (course.constants.ParticipationPermission["issue_exam_ticket"], "Issue exam ticket"), (course.constants.ParticipationPermission["batch_issue_exam_ticket"], "Batch issue exam ticket"), (course.constants.ParticipationPermission["view_participant_masked_profile"], "View participants' masked profile only"), (course.constants.ParticipationPermission["view_flow_sessions_from_role"], "View flow sessions from role"), (course.constants.ParticipationPermission["view_gradebook"], "View gradebook"), (course.constants.ParticipationPermission["edit_grading_opportunity"], "Edit grading opportunity"), (course.constants.ParticipationPermission["assign_grade"], "Assign grade"), (course.constants.ParticipationPermission["view_grader_stats"], "View grader stats"), (course.constants.ParticipationPermission["batch_import_grade"], "Batch-import grades"), (course.constants.ParticipationPermission["batch_export_grade"], "Batch-export grades"), (course.constants.ParticipationPermission["batch_download_submission"], "Batch-download submissions"), (course.constants.ParticipationPermission["impose_flow_session_deadline"], "Impose flow session deadline"), (course.constants.ParticipationPermission["batch_impose_flow_session_deadline"], "Batch-impose flow session deadline"), (course.constants.ParticipationPermission["end_flow_session"], "End flow session"), (course.constants.ParticipationPermission["batch_end_flow_session"], "Batch-end flow sessions"), (course.constants.ParticipationPermission["regrade_flow_session"], "Regrade flow session"), (course.constants.ParticipationPermission["batch_regrade_flow_session"], "Batch-regrade flow sessions"), (course.constants.ParticipationPermission["recalculate_flow_session_grade"], "Recalculate flow session grade"), (course.constants.ParticipationPermission["batch_recalculate_flow_session_grade"], "Batch-recalculate flow session grades"), (course.constants.ParticipationPermission["batch_ai_grade_flow_page"], "Batch AI-draft grades for a flow page"), (course.constants.ParticipationPermission["reopen_flow_session"], "Reopen flow session"), (course.constants.ParticipationPermission["grant_exception"], "Grant exception"), (course.constants.ParticipationPermission["view_analytics"], "View analytics"), (course.constants.ParticipationPermission["preview_content"], "Preview content"), (course.constants.ParticipationPermission["update_content"], "Update content"), (course.constants.ParticipationPermission["use_git_endpoint"], "Use direct git endpoint"), (course.constants.ParticipationPermission["use_markup_sandbox"], "Use markup sandbox"), (course.constants.ParticipationPermission["use_page_sandbox"], "Use page sandbox"), (course.constants.ParticipationPermission["test_flow"], "Test flow"), (course.constants.ParticipationPermission["edit_events"], "Edit events"), (course.constants.ParticipationPermission["query_participation"], "Query participation"), (course.constants.ParticipationPermission["edit_participation"], "Edit participation"), (course.constants.ParticipationPermission["preapprove_participation"], "Preapprove participation"), (course.constants.ParticipationPermission["manage_instant_flow_requests"], "Manage instant flow requests")], db_index=True, max_length=200, verbose_name="Permission"),
        ),
        migrations.RunPython(add_batch_ai_grade_flow_page_permission),
    ]
