apiVersion: v1
kind: Service
metadata:
  name: {{ include "relate.fullname" . }}
  namespace: {{ include "relate.namespace" . }}
  labels: {{- include "relate.labels" . | nindent 4 }}
    {{- if .Values.service.labels }}
    {{- include "relate.render" ( dict "value" .Values.service.labels "context" $) | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.nodePort)) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- else if eq .Values.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    - name: nginx
      port: {{ .Values.service.port }}
      targetPort: 8001
      port: 8001
  selector: {{- include "relate.matchLabels" . | nindent 4 }}



