# Generated by Django 1.11.5 on 2017-09-21 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_change_username_validator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='git_auth_token_hash',
        ),
    ]
