# Generated by Django 4.2.14 on 2024-07-24 19:16

from django.db import migrations, models


def switch_sublime_to_default(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(editor_mode="sublime").update(editor_mode="default")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.RunPython(switch_sublime_to_default),
        migrations.AlterField(
            model_name='user',
            name='editor_mode',
            field=models.CharField(choices=[('default', 'Default'), ('emacs', 'Emacs'), ('vim', 'Vim')], default='default', help_text="Which key bindings you prefer when editing larger amounts of text or code. (If you do not understand what this means, leave it as 'Default'.)", max_length=20, verbose_name='Editor mode'),
        ),
    ]
