name: xeus-python-kernel
channels:
# view these URLs in a browser to see package availability
  - https://prefix.dev/emscripten-forge-4x
  - https://prefix.dev/conda-forge
dependencies:
- xeus-python
- traitlets >=5.9
- typing_extensions >=4.6
- python >=3.13
- numpy
- scipy
- matplotlib
- sympy
