# Generated by Django 5.1 on 2024-10-09 19:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prairietest', '0002_mostrecentdenyevent_end_alter_denyevent_end_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allowevent',
            old_name='test_facility',
            new_name='facility',
        ),
        migrations.RenameField(
            model_name='denyevent',
            old_name='test_facility',
            new_name='facility',
        ),
        migrations.AlterField(
            model_name='facility',
            name='identifier',
            field=models.CharField(db_index=True, max_length=200, unique=True, validators=[django.core.validators.RegexValidator('^(?P<facility_id>[a-zA-Z][a-zA-Z0-9_]*)$')]),
        ),
    ]
