#! /usr/bin/env python3

# placate flake8
from __future__ import print_function

__copyright__ = "Copyright (C) 2014 Andreas Kloeckner"

__license__ = """
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
"""

import socket
import socketserver
import json
import sys
import io
import errno
from cfrunpy_backend import dict_to_struct, run_code, package_exception
from http.server import BaseHTTPRequestHandler

PORT = 9941


class RunRequestHandler(BaseHTTPRequestHandler):
    def do_POST(self):
        response = {}

        prev_stdout = sys.stdout  # noqa
        prev_stderr = sys.stderr  # noqa

        try:
            print("POST RECEIVED", file=prev_stderr)
            if self.path != "/run-python":
                raise RuntimeError("unrecognized path")

            clength = int(self.headers['content-length'])
            recv_data = self.rfile.read(clength)

            print("CFRUNPY RECEIVED %d bytes" % len(recv_data),
                    file=prev_stderr)
            run_req = dict_to_struct(json.loads(recv_data.decode("utf-8")))
            print("REQUEST: %r" % run_req, file=prev_stderr)

            stdout = io.StringIO()
            stderr = io.StringIO()

            sys.stdin = None
            sys.stdout = stdout
            sys.stderr = stderr

            run_code(response, run_req)

            response["stdout"] = stdout.getvalue()
            response["stderr"] = stderr.getvalue()

            print("REQUEST SERVICED: %r" % response, file=prev_stderr)

            json_result = json.dumps(response).encode("utf-8")

            self.send_response(200)
            self.send_header("Content-type", "application/json")
            self.end_headers()

            self.wfile.write(json_result)
        except:
            print("ERROR RESPONSE", file=prev_stderr)
            response = {}
            package_exception(response, "uncaught_error")
            json_result = json.dumps(response).encode("utf-8")

            self.send_response(500)
            self.send_header("Content-type", "application/json")
            self.end_headers()

            self.wfile.write(json_result)
        finally:
            sys.stdout = prev_stdout
            sys.stderr = prev_stderr


def main():
    print("STARTING, LISTENING ON %d" % PORT, file=sys.stderr)
    server = socketserver.TCPServer(("", PORT), RunRequestHandler)

    if len(sys.argv) > 1 and sys.argv[1] == "-1":
        try:
            server.handle_request()
            print("DONE serving requests", file=sys.stderr)
        finally:
            server.server_close()
            print("FINISHED server_close()", file=sys.stderr)
    else:
        server.serve_forever()

    print("EXITING", file=sys.stderr)


if __name__ == "__main__":
    main()

# vim: foldmethod=marker
